import { Navigation } from "@/components/Navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { TrendingUp, AlertTriangle, ShieldCheck, CheckCircle2, ArrowRight } from "lucide-react";

export default function InsightsPage() {
  return (
    <div className="flex min-h-screen bg-background text-foreground">
      <Navigation />

      <main className="flex-1 p-8 max-w-6xl mx-auto space-y-8 overflow-y-auto">
        <header className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Insights & Interventions</h1>
            <p className="text-muted-foreground">Actionable early-warning guidance to change your financial trajectory before crisis.</p>
          </div>
          <span className="bg-primary/10 border border-primary/30 text-primary font-mono text-xs px-3 py-1.5 rounded-full font-bold">
            Intervention Engine Level 3 Active
          </span>
        </header>

        {/* HIGH PRIORITY TODAY RECOMMENDATION */}
        <Card className="border-red-500/50 bg-red-500/5">
          <CardHeader>
            <div className="flex justify-between items-start">
              <span className="text-xs font-bold text-red-400 bg-red-500/20 px-3 py-1 rounded-full uppercase tracking-wider">
                TODAY — HIGH PRIORITY
              </span>
              <span className="text-xs text-muted-foreground font-mono">Generated by Distress-v2.1</span>
            </div>
            <CardTitle className="text-2xl font-bold text-foreground mt-2">
              Protect upcoming EMI payment (₹4,500 due in 8 days)
            </CardTitle>
            <CardDescription className="text-sm">
              Your recent income is 18% below your usual baseline and your liquid buffer is limited (9 days).
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-background border border-border flex justify-between items-center">
                <div>
                  <div className="font-bold text-sm">Action 1: Lock ₹4,500 for EMI</div>
                  <div className="text-xs text-muted-foreground">Earmark platform payouts directly</div>
                </div>
                <Button size="sm" className="rounded-full text-xs font-bold">Accept Plan</Button>
              </div>

              <div className="p-4 rounded-xl bg-background border border-border flex justify-between items-center">
                <div>
                  <div className="font-bold text-sm">Action 2: Cut Discretionary by ₹1,000</div>
                  <div className="text-xs text-muted-foreground">Temporary hold on dining & non-essentials</div>
                </div>
                <Button size="sm" variant="outline" className="rounded-full text-xs font-bold">Review Spending</Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* CASH FLOW FORECAST RANGE (SECTION 41 & 53) */}
        <Card className="border-border bg-card/60">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              <span>30-Day Cash Flow Forecast Range</span>
            </CardTitle>
            <CardDescription>Predicting income ranges rather than static single numbers for irregular workers</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="p-4 rounded-xl bg-secondary/50 border border-border">
                <span className="text-xs text-muted-foreground font-semibold uppercase">Expected Income</span>
                <div className="text-2xl font-black text-foreground mt-1">₹21,000 – ₹25,000</div>
                <span className="text-[11px] text-primary font-medium">Conservative: ₹21,800</span>
              </div>

              <div className="p-4 rounded-xl bg-secondary/50 border border-border">
                <span className="text-xs text-muted-foreground font-semibold uppercase">Essential Expenses</span>
                <div className="text-2xl font-black text-foreground mt-1">₹17,800</div>
                <span className="text-[11px] text-muted-foreground">Fixed baseline</span>
              </div>

              <div className="p-4 rounded-xl bg-secondary/50 border border-border">
                <span className="text-xs text-muted-foreground font-semibold uppercase">Debt Obligations</span>
                <div className="text-2xl font-black text-foreground mt-1">₹5,000</div>
                <span className="text-[11px] text-yellow-500 font-medium">2 Loan EMIs</span>
              </div>

              <div className="p-4 rounded-xl bg-secondary/50 border border-border">
                <span className="text-xs text-muted-foreground font-semibold uppercase">Projected Buffer</span>
                <div className="text-2xl font-black text-primary mt-1">₹3,200</div>
                <span className="text-[11px] text-muted-foreground">Estimated surplus</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
